Repository gradsflow/gradsflow, pull requests merged in 2022-01, with the labels that each got.

#153 refactor Tracker
  examples/src/tasks/image_classifier.py
  gradsflow/callbacks/base.py
  gradsflow/callbacks/gpu.py
  gradsflow/callbacks/logger/comet.py
  gradsflow/callbacks/logger/logger.py
  gradsflow/callbacks/progress.py
  gradsflow/callbacks/raytune.py
  gradsflow/callbacks/runner.py
  gradsflow/callbacks/training.py
  gradsflow/core/__init__.py
  gradsflow/core/base.py
  gradsflow/models/base.py
  gradsflow/models/model.py
  gradsflow/models/tracker.py
  gradsflow/utility/common.py
  tests/callbacks/test_runner.py
  tests/conftest.py
  tests/models/test_tracker.py
Labels: API design, code health

#158 📝 fix documentation & examples
  examples/nbs/01-ImageClassification.ipynb
  examples/nbs/05-model_fit.ipynb
  examples/src/models/hello_world.py
  gradsflow/models/base.py
  gradsflow/models/model.py
  tests/models/test_model.py
Labels: test, example

#162 fix model checkpoint folder not found
  gradsflow/callbacks/logger/logger.py
  tests/callbacks/test_logger.py
Labels: bug / fix, test

#169 increment current_epoch after each epoch
  gradsflow/models/model.py
Labels: bug / fix

#168 Wandb Implementation
  docs/requirements.txt
  gradsflow/callbacks/__init__.py
  gradsflow/callbacks/comet.py
  gradsflow/callbacks/logger.py
  gradsflow/callbacks/wandb.py
  gradsflow/core/base.py
  gradsflow/models/model.py
  gradsflow/models/tracker.py
  gradsflow/utility/common.py
  setup.cfg
  tests/autotasks/__init__.py
  tests/callbacks/__init__.py
  tests/callbacks/test_logger.py
  tests/callbacks/test_runner.py
  tests/callbacks/test_wandb.py
  tests/conftest.py
  tests/utility/test_common.py
Labels: documentation, enhancement, test

#170 🌟 format docs
  docs/CHANGELOG.md
  docs/gradsflow/callbacks.md
  gradsflow/callbacks/__init__.py
  gradsflow/callbacks/comet.py
  gradsflow/callbacks/logger.py
  gradsflow/callbacks/training.py
  gradsflow/callbacks/wandb.py
Labels: documentation

#173 Tensorboard callbacks
  docs/CHANGELOG.md
  docs/requirements.txt
  gradsflow/callbacks/__init__.py
  gradsflow/callbacks/tensorboard.py
Labels: documentation, enhancement
